### ISSUE TITLE
Error for all tagrity commands

### ISSUE THREAD

**Issue by RRethy** [RRethy/tagrity#4]
```
Traceback (most recent call last):
	31: from /Users/rethy/.rbenv/versions/2.6.3/bin/tagrity:23:in `<main>'
	30: from /Users/rethy/.rbenv/versions/2.6.3/bin/tagrity:23:in `load'
	29: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/tagrity-0.2.10/exe/tagrity:3:in `<top (required)>'
	28: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	27: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	26: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/tagrity-0.2.10/lib/tagrity/cli.rb:2:in `<top (required)>'
	25: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	24: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	23: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/tagrity-0.2.10/lib/tagrity/commands/start.rb:1:in `<top (required)>'
	22: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	21: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	20: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/listen-3.2.1/lib/listen.rb:3:in `<top (required)>'
	19: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	18: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	17: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/listen-3.2.1/lib/listen/listener.rb:5:in `<top (required)>'
	16: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	15: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/listen-3.2.1/lib/listen/backend.rb:1:in `<top (required)>'
	13: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/listen-3.2.1/lib/listen/adapter.rb:1:in `<top (required)>'
	10: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	9: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	8: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/listen-3.2.1/lib/listen/adapter/base.rb:3:in `<top (required)>'
	7: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	6: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	5: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/listen-3.2.1/lib/listen/change.rb:1:in `<top (required)>'
	4: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/listen-3.2.1/lib/listen/file.rb:1:in `<top (required)>'
	1: from /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/rethy/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/rethy/.rbenv/versions/2.6.3/lib/ruby/2.6.0/x86_64-darwin16/digest/md5.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (LoadError)
  Referenced from: /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/2.6.0/x86_64-darwin16/digest/md5.bundle
  Reason: image not found - /Users/rethy/.rbenv/versions/2.6.3/lib/ruby/2.6.0/x86_64-darwin16/digest/md5.bundle
```

**Comment by RRethy** [comment]
Issue with my installation of ruby.
