### ISSUE TITLE
Argument error when running tagrity start

### ISSUE THREAD

**Issue by ittisafur** [RRethy/tagrity#6]
**OS: Ubuntu 20.04
Ruby Version: 3.0.1p64
Used Rbenv to install ruby**

Installed via `gem install tagrity`
When i run the command 
`tagrity start`
I get this following errors not sure what to do
```
/home/undefined/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tagrity-0.2.13/lib/tagrity/commands/start.rb:18:in "daemon": true or false is expected as nochdir: {:nochdir=>true} (ArgumentError)
	from /home/undefined/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tagrity-0.2.13/lib/tagrity/commands/start.rb:18:in "call"
	from /home/undefined/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tagrity-0.2.13/lib/tagrity/cli.rb:13:in "start"
	from /home/undefined/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-0.20.3/lib/thor/command.rb:27:in "run"
	from /home/undefined/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in "invoke_command"
	from /home/undefined/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-0.20.3/lib/thor.rb:387:in "dispatch"
	from /home/undefined/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-0.20.3/lib/thor/base.rb:466:in "start"
	from /home/undefined/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tagrity-0.2.13/exe/tagrity:4:in "<top (required)>"
	from /home/undefined/.rbenv/versions/3.0.1/bin/tagrity:23:in "load"
	from /home/undefined/.rbenv/versions/3.0.1/bin/tagrity:23:in "<main>"
```
I'm not a ruby developer so a bit guidance would be helpful if this problem is not connected with the package.

**Comment by RRethy** [comment]
Looks like a ruby 3 problem, https://rubyreferences.github.io/rubychanges/3.0.html#language-changes. I'll update this later today and release a new version that uses Ruby 3 compatible syntax. (For reference, I've been using Ruby 2.6) In the meantime if you are able to downgrade to Ruby 2.6 it should work.

**Comment by ittisafur** [comment]
Downgrading to 2.6.7 worked. Thank you so much.

**Comment by RRethy** [comment]
Reopening since i do want to fix this for ruby v3.
